#!/usr/bin/env python3
import pathlib
import re
import sys

if len(sys.argv) != 3:
    raise SystemExit("usage: patch_portrait.py portrait.xml ui.xml")

portrait = pathlib.Path(sys.argv[1])
ui = pathlib.Path(sys.argv[2])

p = portrait.read_text()
u = ui.read_text()

# Remove old custom MixedSD pages.  Do NOT touch Advanced or partsdcardsel.
for name in (
    "xz1c_sd_menu",
    "xz1c_sd_config",
    "xz1c_sd_format",
):
    p = re.sub(
        r'\s*<page\s+name="' + re.escape(name) +
        r'">.*?</page>\s*',
        "\n",
        p,
        flags=re.S,
    )

# Remove variables generated by previous MixedSD revisions.
variables = (
    "tw_xz1c_sd_loaded",
    "tw_xz1c_sd_total_gib",
    "tw_xz1c_sd_total_display",
    "tw_xz1c_sd_status",
    "tw_xz1c_sd_layout",
    "tw_xz1c_sd_alloc_gib",
    "tw_xz1c_sd_device",
    "tw_xz1c_sd_sector",
    "tw_xz1c_sd_bytes",
    "tw_xz1c_sd_app_gib",
    "tw_xz1c_sd_public_gib",
    "tw_xz1c_sd_swap_gib",
    "tw_xz1c_sd_app_on",
    "tw_xz1c_sd_public_on",
    "tw_xz1c_sd_swap_on",
)

for name in variables:
    u = re.sub(
        r'\s*<variable\s+name="' +
        re.escape(name) +
        r'"[^>]*/>\s*',
        "\n",
        u,
    )

if "</variables>" not in u:
    raise SystemExit("ui.xml: </variables> not found")

vars_xml = r"""
<variable name="tw_xz1c_sd_loaded" value="0"/>
<variable name="tw_xz1c_sd_total_gib" value="0"/>
<variable name="tw_xz1c_sd_total_display" value="Not loaded"/>
<variable name="tw_xz1c_sd_status" value="Load SD first"/>
<variable name="tw_xz1c_sd_layout" value="none"/>
<variable name="tw_xz1c_sd_alloc_gib" value="0"/>
<variable name="tw_xz1c_sd_device" value="/dev/block/mmcblk0"/>
<variable name="tw_xz1c_sd_sector" value="512"/>
<variable name="tw_xz1c_sd_bytes" value="0"/>

<variable name="tw_xz1c_sd_app_gib" value="0"/>
<variable name="tw_xz1c_sd_public_gib" value="0"/>
<variable name="tw_xz1c_sd_swap_gib" value="0"/>

<variable name="tw_xz1c_sd_app_on" value="1"/>
<variable name="tw_xz1c_sd_public_on" value="1"/>
<variable name="tw_xz1c_sd_swap_on" value="0"/>

<variable name="tw_xz1c_sd_full_mode" value="0"/>

<!-- MixedSD portrait-only Y coordinates -->
<variable name="tw_mixed_app_label_y" value="620"/>
<variable name="tw_mixed_app_slider_y" value="760"/>

<variable name="tw_mixed_public_label_y" value="940"/>
<variable name="tw_mixed_public_slider_y" value="1080"/>

<variable name="tw_mixed_swap_label_y" value="1260"/>
<variable name="tw_mixed_swap_slider_y" value="1400"/>

<variable name="tw_mixed_selected_y" value="1540"/>
<variable name="tw_mixed_unallocated_y" value="1580"/>

<variable name="tw_mixed_buttons_y" value="1680"/>
<variable name="tw_xz1c_sd_selected_gib" value="0"/>
<variable name="tw_xz1c_sd_unallocated_gib" value="0"/>
"""

u = u.replace(
    "</variables>",
    vars_xml + "\n</variables>",
    1,
)

# ----------------------------------------------------------------------
# Stock partsdcard page replacement.
#
# Advanced -> Partition SD card -> partsdcardsel -> partsdcard
#
# Only partsdcard is replaced.
# ----------------------------------------------------------------------

new_page = r"""<page name="partsdcard">
<template name="page"/>
<text style="text_l"><placement x="%col1_x_header%" y="%row3_header_y%"/><text>Mixed SD Card</text></text>
<text style="text_m"><placement x="%col1_x_header%" y="%row4_header_y%"/><text>Load SD to read its capacity</text></text>

<text style="text_m"><placement x="%indent%" y="%row8_y%"/><text>Capacity: %tw_xz1c_sd_total_display%</text></text>
<text style="text_m_accent"><placement x="%indent%" y="%row9a_y%"/><text>%tw_xz1c_sd_status%</text></text>

<button style="checkbox"><placement x="%indent%" y="%tw_mixed_app_label_y%" textplacement="6"/><text>App / Internal (F2FS): %tw_xz1c_sd_app_gib% GiB</text><condition var1="tw_xz1c_sd_app_on" var2="0"/><image resource="checkbox_false"/><actions><action function="set">tw_xz1c_sd_app_on=1</action><action function="cmd">/sbin/xz1c_mixed_sd_probe.sh rebalance toggle app</action><action function="page">partsdcard</action></actions></button>
<button style="checkbox"><placement x="%indent%" y="%tw_mixed_app_label_y%" textplacement="6"/><text>App / Internal (F2FS): %tw_xz1c_sd_app_gib% GiB</text><condition var1="tw_xz1c_sd_app_on" op="!=" var2="0"/><image resource="checkbox_true"/><actions><action function="set">tw_xz1c_sd_app_on=0</action><action function="set">tw_xz1c_sd_app_gib=0</action><action function="cmd">/sbin/xz1c_mixed_sd_probe.sh rebalance toggle app</action><action function="page">partsdcard</action></actions></button>
<input><condition var1="tw_xz1c_sd_app_on" var2="1"/><placement x="760" y="%tw_mixed_app_label_y%" w="220" h="%input_height%"/><text>%tw_xz1c_sd_app_gib%</text><data name="tw_xz1c_sd_app_gib"/><restrict minlen="1" maxlen="6" allow="0123456789"/><alignment>center</alignment><actions><action function="cmd">/sbin/xz1c_mixed_sd_probe.sh rebalance value app</action><action function="page">partsdcard</action></actions></input>
<slidervalue><condition var1="tw_xz1c_sd_app_on" var2="1"/><placement x="%indent%" y="%tw_mixed_app_slider_y%" w="%content_width%"/><data variable="tw_xz1c_sd_app_gib" min="0" max="%tw_xz1c_sd_alloc_gib%"/><actions><action function="cmd">/sbin/xz1c_mixed_sd_probe.sh rebalance value app</action><action function="page">partsdcard</action></actions></slidervalue>


<button style="checkbox"><placement x="%indent%" y="%tw_mixed_public_label_y%" textplacement="6"/><text>Download / Public (exFAT): %tw_xz1c_sd_public_gib% GiB</text><condition var1="tw_xz1c_sd_public_on" var2="0"/><image resource="checkbox_false"/><actions><action function="set">tw_xz1c_sd_public_on=1</action><action function="cmd">/sbin/xz1c_mixed_sd_probe.sh rebalance toggle public</action><action function="page">partsdcard</action></actions></button>
<button style="checkbox"><placement x="%indent%" y="%tw_mixed_public_label_y%" textplacement="6"/><text>Download / Public (exFAT): %tw_xz1c_sd_public_gib% GiB</text><condition var1="tw_xz1c_sd_public_on" op="!=" var2="0"/><image resource="checkbox_true"/><actions><action function="set">tw_xz1c_sd_public_on=0</action><action function="set">tw_xz1c_sd_public_gib=0</action><action function="cmd">/sbin/xz1c_mixed_sd_probe.sh rebalance toggle public</action><action function="page">partsdcard</action></actions></button>
<input><condition var1="tw_xz1c_sd_public_on" var2="1"/><placement x="760" y="%tw_mixed_public_label_y%" w="220" h="%input_height%"/><text>%tw_xz1c_sd_public_gib%</text><data name="tw_xz1c_sd_public_gib"/><restrict minlen="1" maxlen="6" allow="0123456789"/><alignment>center</alignment><actions><action function="cmd">/sbin/xz1c_mixed_sd_probe.sh rebalance value public</action><action function="page">partsdcard</action></actions></input>
<slidervalue><condition var1="tw_xz1c_sd_public_on" var2="1"/><placement x="%indent%" y="%tw_mixed_public_slider_y%" w="%content_width%"/><data variable="tw_xz1c_sd_public_gib" min="0" max="%tw_xz1c_sd_alloc_gib%"/><actions><action function="cmd">/sbin/xz1c_mixed_sd_probe.sh rebalance value public</action><action function="page">partsdcard</action></actions></slidervalue>


<button style="checkbox"><placement x="%indent%" y="%tw_mixed_swap_label_y%" textplacement="6"/><text>Swap (Linux swap): %tw_xz1c_sd_swap_gib% GiB</text><condition var1="tw_xz1c_sd_swap_on" var2="0"/><image resource="checkbox_false"/><actions><action function="set">tw_xz1c_sd_swap_on=1</action><action function="cmd">/sbin/xz1c_mixed_sd_probe.sh rebalance toggle swap</action><action function="page">partsdcard</action></actions></button>
<button style="checkbox"><placement x="%indent%" y="%tw_mixed_swap_label_y%" textplacement="6"/><text>Swap (Linux swap): %tw_xz1c_sd_swap_gib% GiB</text><condition var1="tw_xz1c_sd_swap_on" op="!=" var2="0"/><image resource="checkbox_true"/><actions><action function="set">tw_xz1c_sd_swap_on=0</action><action function="set">tw_xz1c_sd_swap_gib=0</action><action function="cmd">/sbin/xz1c_mixed_sd_probe.sh rebalance toggle swap</action><action function="page">partsdcard</action></actions></button>
<input><condition var1="tw_xz1c_sd_swap_on" var2="1"/><placement x="760" y="%tw_mixed_swap_label_y%" w="220" h="%input_height%"/><text>%tw_xz1c_sd_swap_gib%</text><data name="tw_xz1c_sd_swap_gib"/><restrict minlen="1" maxlen="6" allow="0123456789"/><alignment>center</alignment><actions><action function="cmd">/sbin/xz1c_mixed_sd_probe.sh rebalance value swap</action><action function="page">partsdcard</action></actions></input>
<slidervalue><condition var1="tw_xz1c_sd_swap_on" var2="1"/><placement x="%indent%" y="%tw_mixed_swap_slider_y%" w="%content_width%"/><data variable="tw_xz1c_sd_swap_gib" min="0" max="%tw_xz1c_sd_alloc_gib%"/><actions><action function="cmd">/sbin/xz1c_mixed_sd_probe.sh rebalance value swap</action><action function="page">partsdcard</action></actions></slidervalue>


<text style="text_m"><placement x="%indent%" y="%tw_mixed_selected_y%"/><text>Selected: %tw_xz1c_sd_selected_gib% GiB / %tw_xz1c_sd_alloc_gib% GiB</text></text>
<text style="text_m"><placement x="%indent%" y="%tw_mixed_unallocated_y%"/><text>Unallocated: %tw_xz1c_sd_unallocated_gib% GiB</text></text>

<button style="button_third_width"><placement x="%indent%" y="%tw_mixed_buttons_y%"/><text>Configure Mixed SD</text><actions><action function="set">tw_back=partsdcard</action><action function="set">tw_action=cmd</action><action function="set">tw_action_param=/sbin/xz1c_mixed_sd_partition.sh %tw_xz1c_sd_app_gib% %tw_xz1c_sd_public_gib% %tw_xz1c_sd_swap_gib%</action><action function="set">tw_text1=Create Mixed SD layout?</action><action function="set">tw_text2=Existing SD partitions will be replaced.</action><action function="set">tw_action_text1=Configuring Mixed SD...</action><action function="set">tw_complete_text1=Mixed SD configuration complete</action><action function="set">tw_slider_text=Swipe to Confirm</action><action function="page">confirm_action</action></actions></button>
<button style="button_third_width"><placement x="%btn3_col2_x%" y="%tw_mixed_buttons_y%"/><text>Format</text><actions><action function="set">tw_back=partsdcard</action><action function="set">tw_action=cmd</action><action function="set">tw_action_param=/sbin/xz1c_mixed_sd_partition.sh %tw_xz1c_sd_app_gib% %tw_xz1c_sd_public_gib% %tw_xz1c_sd_swap_gib%</action><action function="set">tw_text1=Format SD with this layout?</action><action function="set">tw_text2=Existing SD partitions will be replaced.</action><action function="set">tw_action_text1=Formatting SD...</action><action function="set">tw_complete_text1=SD format complete</action><action function="set">tw_slider_text=Swipe to Confirm</action><action function="page">confirm_action</action></actions></button>
<button style="button_third_width"><placement x="%btn3_col3_x%" y="%tw_mixed_buttons_y%"/><text>Load SD</text><actions><action function="cmd">/sbin/xz1c_mixed_sd_probe.sh</action><action function="page">partsdcard</action></actions></button>

<action><touch key="back"/><action function="page">partsdcardsel</action></action>
</page>"""

match = re.search(
    r'<page\s+name="partsdcard">.*?</page>',
    p,
    flags=re.S,
)

if not match:
    raise SystemExit("ERROR: stock partsdcard page not found")

p = (
    p[:match.start()]
    + new_page.strip()
    + p[match.end():]
)

portrait.write_text(p)
ui.write_text(u)

print("OK: patched stock partsdcard page")
